version: "3"

services:

  webid-auth-db:
    container_name: webid-auth-db
    image: mysql:latest
    networks:
      - auth
    environment:
      - MYSQL_ROOT_PASSWORD=${WEBID_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WEBID_MYSQL_DB_NAME}
      - MYSQL_USER=${WEBID_MYSQL_USERNAME}
      - MYSQL_PASSWORD=${WEBID_MYSQL_PASSWORD}
    ports:
      - 3306:3306
  webid-auth:
    container_name: webid-auth
    image: jboss/keycloak:latest
    networks:
      - frontend
      - auth
    environment:
        - DB_VENDOR=mysql
        - DB_ADDR=webid-auth-db
        - DB_PORT=3306
        - DB_DATABASE=${WEBID_MYSQL_DB_NAME}
        - DB_USER=${WEBID_MYSQL_USERNAME}
        - DB_PASSWORD=${WEBID_MYSQL_PASSWORD}
        - KEYCLOAK_USER=${WEBID_KEYCLOAK_USERNAME}
        - KEYCLOAK_PASSWORD=${WEBID_KEYCLOAK_PASSWORD}
    volumes:
      - ./webid_auth/custom-login:/opt/jboss/keycloak/themes/webid-login
      #- ./webid_auth/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
    ports:
      - 8070:8080
      - 8443:8443
      - 9990:9990
    depends_on:
      - webid_auth_db

  webid-db:
    container_name: webid-db
    networks:
      - backend
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${WEBID_MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${WEBID_MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=WebID_DB
    volumes:
      - ./webid_db/db:/data/db
    ports:
      - 2717:27017
    command: --quiet --logpath /data/db/logs
    
  webid-server:
    container_name: webid-server
    networks:
      - frontend
      - backend
    environment:
      - MONGO_LOGIN=${WEBID_MONGO_USERNAME}
      - MONGO_PASSWORD=${WEBID_MONGO_PASSWORD}
    build: 
      context: "./webid_server"
      target: "dev-stage"
    volumes:
      - ./webid_server/src:/usr/src/app/src
      - ./webid_server/temporary:/usr/src/app/temporary
    ports:
      - 3000:3000
    depends_on:
      - webid-db
      - webid_auth
  webid-client:
    container_name: webid-client
    networks:
      - frontend
    build: 
      context: "./webid_client"
      target: 'dev-stage'
    volumes:
      - ./webid_client/src:/app/src
    ports:
      - 8080:8080
    #command: /bin/sh -c "yarn serve"
    depends_on:
      - webid-server
      - webid_auth
networks:
  frontend:
  backend:
  auth:
